/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GETApiSchema {
  endpoints: {
    "GET /api": {
      description: string;
      [k: string]: unknown;
    };
    "GET /api/articles": {
      description: string;
      queries: string[];
      exampleResponse: {
        articles: {
          author: string;
          title: string;
          article_id: number;
          topic: string;
          created_at: string;
          votes: number;
          article_img_url: string;
          comment_count: number;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    "Post /api/articles": {
      description: string;
      exampleRequest: {
        author: string;
        title: string;
        body: string;
        topic: string;
        article_img_url: string;
        [k: string]: unknown;
      };
      exampleResponse: {
        article: {
          article_id: number;
          title: string;
          topic: string;
          author: string;
          body: string;
          created_at: string;
          votes: number;
          article_img_url: string;
          [k: string]: unknown;
        };
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    "GET /api/articles/:article_id": {
      description: string;
      queries: unknown[];
      exampleResponse: {
        articles: {
          title: string;
          topic: string;
          author: string;
          body: string;
          created_at: string;
          votes: number;
          comment_count: number;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    "PATCH /api/articles/:article_id": {
      description: string;
      queries: unknown[];
      exampleRequest: {
        addOrRemoveVotes: number;
        [k: string]: unknown;
      };
      exampleResponse: {
        article: {
          title: string;
          topic: string;
          author: string;
          body: string;
          created_at: string;
          votes: number;
          comment_count: number;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    "GET /api/articles/:article_id/comments": {
      description: string;
      queries: unknown[];
      exampleResponse: {
        articles: {
          comment_id: number;
          votes: number;
          created_at: string;
          author: string;
          body: string;
          article_id: number;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    "POST /api/articles/:article_id/comments": {
      description: string;
      queries: unknown[];
      exampleRequest: {
        author: string;
        body: string;
        [k: string]: unknown;
      };
      exampleResponse: {
        comment: {
          comment: string;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    "DELETE /api/comments/:comment_id": {
      description: string;
      queries: unknown[];
      exampleResponse: {
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    "GET /api/topics": {
      description: string;
      queries: unknown[];
      exampleResponse: {
        topics: {
          slug: string;
          description: string;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    "GET /api/users": {
      description: string;
      queries: unknown[];
      exampleResponse: {
        topics: {
          username: string;
          name: string;
          avatar_url: string;
          [k: string]: unknown;
        }[];
        [k: string]: unknown;
      };
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
